### ISSUE TITLE
[Question] When do you plan to rebuild and release recent changes ?

### ISSUE THREAD

**Issue by raskyer** [Outpost-21/Asimov#7]
Hello, do you have an ETA for the build and upload of the recent changes to the Steam Workshop? It's not particularly urgent, but it would help resolve a frustrating issue with Automatons' pathing.

(For reference : https://github.com/Outpost-21/Asimov/pull/1)

Thanks again for your work !

**Comment by neronix17** [comment]
About 30 seconds ago. I push fixes as soon as I have the time to do some basic testing and I didn't have the time till today due to medical issues.
